agent1:
  idx: 1
  in_neigh: !!set
    4: null
    8: null
    12: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 9.354501485154353
    - 0.0
  - - 0.0
    - 9.354501485154353
  n_i: 2
  out_neigh: !!set
    2: null
  p_i: 2
  x_0: [1, 1]
  x_H:
  - -0.10915773818550956
  - -0.012081620486752653

agent2:
  idx: 2
  in_neigh: !!set
    1: null
    11: null
    12: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 3.225733209565602
    - 0.0
  - - 0.0
    - 3.225733209565602
  n_i: 2
  out_neigh: !!set
    10: null
  p_i: 2
  x_0: [-1, -1]
  x_H:
  - -0.19556592838445042
  - -0.6316197060123396
agent3:
  idx: 3
  in_neigh: !!set
    7: null
    10: null
    11: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 2.0834666770706276
    - 0.0
  - - 0.0
    - 2.0834666770706276
  n_i: 2
  out_neigh: !!set
    4: null
    6: null
    10: null
  p_i: 2
  x_0: [1, -1]
  x_H:
  - -0.39168011258465407
  - -0.21812848584250455
agent4:
  idx: 4
  in_neigh: !!set
    3: null
    6: null
    9: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 0.32536014468502295
    - 0.0
  - - 0.0
    - 0.32536014468502295
  n_i: 2
  out_neigh: !!set
    1: null
    8: null
    9: null
  p_i: 2
  x_0: [-1, 1]
  x_H:
  - -0.7603341861954267
  - 0.2850086183343945
agent5:
  idx: 5
  in_neigh: !!set
    8: null
    9: null
    12: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 4.981717374834615
    - 0.0
  - - 0.0
    - 4.981717374834615
  n_i: 2
  out_neigh: !!set
    8: null
    11: null
    12: null
  p_i: 2
  x_0: [1, 0]
  x_H:
  - 0.649418460676934
  - 0.7333085548946834
agent6:
  idx: 6
  in_neigh: !!set
    3: null
    10: null
    12: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 7.349592620374612
    - 0.0
  - - 0.0
    - 7.349592620374612
  n_i: 2
  out_neigh: !!set
    4: null
    9: null
    11: null
    12: null
  p_i: 2
  x_0: [-1, 0]
  x_H:
  - -0.4203908773375107
  - 0.8633226435746988
agent7:
  idx: 7
  in_neigh: !!set
    10: null
    11: null
    12: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 2.197670579560115
    - 0.0
  - - 0.0
    - 2.197670579560115
  n_i: 2
  out_neigh: !!set
    3: null
    12: null
  p_i: 2
  x_0: [0, 1]
  x_H:
  - 0.31474597668494897
  - -0.7566769205106632
agent8:
  idx: 8
  in_neigh: !!set
    4: null
    5: null
    11: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 9.319016659505788
    - 0.0
  - - 0.0
    - 9.319016659505788
  n_i: 2
  out_neigh: !!set
    1: null
    5: null
  p_i: 2
  x_0: [0, -1]
  x_H:
  - 0.26482537702184583
  - 0.13109588322456567
agent9:
  idx: 9
  in_neigh: !!set
    4: null
    6: null
    11: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 7.172157506330542
    - 0.0
  - - 0.0
    - 7.172157506330542
  n_i: 2
  out_neigh: !!set
    4: null
    5: null
  p_i: 2
  x_0: [-0.5, 1]
  x_H:
  - 0.5581111170634212
  - 0.7736970744077554

agent10:
  idx: 10
  in_neigh: !!set
    2: null
    3: null
    12: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 8.303103432335424
    - 0.0
  - - 0.0
    - 8.303103432335424
  n_i: 2
  out_neigh: !!set
    3: null
    6: null
    7: null
    11: null
  p_i: 2
  x_0: [0.5, 1]
  x_H:
  - -0.27312723649623316
  - -0.18812461726490737
agent11:
  idx: 11
  in_neigh: !!set
    5: null
    6: null
    10: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 7.223657123349679
    - 0.0
  - - 0.0
    - 7.223657123349679
  n_i: 2
  out_neigh: !!set
    2: null
    3: null
    7: null
    8: null
    9: null
  p_i: 2
  x_0: [-0.5, -1]
  x_H:
  - -0.6855040750469314
  - -0.20125723615497892
agent12:
  idx: 12
  in_neigh: !!set
    5: null
    6: null
    7: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 8.8883719776954
    - 0.0
  - - 0.0
    - 8.8883719776954
  n_i: 2
  out_neigh: !!set
    1: null
    2: null
    5: null
    6: null
    7: null
    10: null
  p_i: 2
  x_0: [0.5, -1]
  x_H:
  - 0.6372165127651732
  - -0.7076048988248145
