# Simple network where:
# - 1 affects 2 and 3, is affected by 2
# - 1 affects 1, is affected by 1
# - 3 affects 2, is affected by 1
# - agents have identity dynamics and simple input laws

agent1:
    idx: 1
    n_i: 2
    p_i: 2
    x_0: [1, 1]
    x_H: [0, 0]
    out_neigh: {3, 5}
    in_neigh: {4}
    matA: [[0.5, 0], [0, 0.5]]
    matB: [[1, 0], [0, 1]]
    matA_inter: [[[0.1, 0], [0, 0.1]],[[0.1, 0], [0, 0.1]]] # dynamic A interactions with out-neighbours
    matB_inter: [[[0.1, 0], [0, 0.1]],[[0.1, 0], [0, 0.1]]] # dynamic B interactions with out-neighbours
    matCost: [[2, 0], [0, 2]]
    
agent2:
    idx: 2
    n_i: 2
    p_i: 2
    x_0: [-1, -1]
    x_H: [0, 0.5]
    out_neigh: {}
    in_neigh: {3}
    matA: [[0.5, 0], [0, 0.5]]
    matB: [[1, 0], [0, 1]]
    matA_inter: []  # dynamic A interactions with out-neighbours
    matB_inter: []  # dynamic B interactions with out-neighbours
    matCost: [[2, 0], [0, 2]]

agent3:
    idx: 3
    n_i: 2
    p_i: 2
    x_0: [1, -1]
    x_H: [0.5, 1]
    out_neigh: {2}
    in_neigh: {1}
    matA: [[0.5, 0], [0, 0.5]]
    matB: [[1, 0], [0, 1]]
    matA_inter: [[[0.1, 0], [0, 0.1]]]  # dynamic A interactions with out-neighbours
    matB_inter: [[[0.1, 0], [0, 0.1]]]  # dynamic B interactions with out-neighbours
    matCost: [[2, 0], [0, 2]]

agent4:
    idx: 4
    n_i: 2
    p_i: 2
    x_0: [-1, 1]
    x_H: [-1, 0]
    out_neigh: {1}
    in_neigh: {5}
    matA: [[0.5, 0], [0, 0.5]]
    matB: [[1, 0], [0, 1]]
    matA_inter: [[[0.1, 0], [0, 0.1]]] # dynamic A interactions with out-neighbours
    matB_inter: [[[0.1, 0], [0, 0.1]]] # dynamic B interactions with out-neighbours
    matCost: [[2, 0], [0, 2]]

agent5:
    idx: 5
    n_i: 2
    p_i: 2
    x_0: [1, 0]
    x_H: [0, -1]
    out_neigh: {4}
    in_neigh: {1}
    matA: [[0.5, 0], [0, 0.5]]
    matB: [[1, 0], [0, 1]]
    matA_inter: [[[0.1, 0], [0, 0.1]]] # dynamic A interactions with out-neighbours
    matB_inter: [[[0.1, 0], [0, 0.1]]] # dynamic B interactions with out-neighbours
    matCost: [[2, 0], [0, 2]]