agent1:
  idx: 1
  in_neigh: !!set
    3: null
    8: null
    9: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 8.068108731458317
    - 0.0
  - - 0.0
    - 8.068108731458317
  n_i: 2
  out_neigh: !!set
    8: null
  p_i: 2
  x_0: [1, 1]
  x_H: [0.25, 0]

agent2:
  idx: 2
  in_neigh: !!set
    5: null
    6: null
    8: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 2.262502025509656
    - 0.0
  - - 0.0
    - 2.262502025509656
  n_i: 2
  out_neigh: !!set
    6: null
    8: null
  p_i: 2
  x_0: [-1, -1]
  x_H: [0, 0.5]

agent3:
  idx: 3
  in_neigh: !!set
    5: null
    7: null
    9: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 8.769134337002537
    - 0.0
  - - 0.0
    - 8.769134337002537
  n_i: 2
  out_neigh: !!set
    1: null
    7: null
    8: null
  p_i: 2
  x_0: [1, -1]
  x_H: [0.5, 1]

agent4:
  idx: 4
  in_neigh: !!set
    5: null
    6: null
    8: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 2.6786399946577086
    - 0.0
  - - 0.0
    - 2.6786399946577086
  n_i: 2
  out_neigh: !!set
    6: null
    7: null
    9: null
  p_i: 2
  x_0: [-1, 1]
  x_H: [-1, -0.25]

agent5:
  idx: 5
  in_neigh: !!set
    6: null
    8: null
    9: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 9.813034246736198
    - 0.0
  - - 0.0
    - 9.813034246736198
  n_i: 2
  out_neigh: !!set
    2: null
    3: null
    4: null
    9: null
  p_i: 2
  x_0: [1, 0]
  x_H: [0, -1]

agent6:
  idx: 6
  in_neigh: !!set
    2: null
    4: null
    7: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 7.982744227844999
    - 0.0
  - - 0.0
    - 7.982744227844999
  n_i: 2
  out_neigh: !!set
    2: null
    4: null
    5: null
    9: null
  p_i: 2
  x_0: [-1, 0]
  x_H: [0.5, -0.5]

agent7:
  idx: 7
  in_neigh: !!set
    3: null
    4: null
    8: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 9.96678787595973
    - 0.0
  - - 0.0
    - 9.96678787595973
  n_i: 2
  out_neigh: !!set
    3: null
    6: null
  p_i: 2
  x_0: [0, 1]
  x_H: [-0.25, 0.5]
  
agent8:
  idx: 8
  in_neigh: !!set
    1: null
    2: null
    3: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 4.542619556254522
    - 0.0
  - - 0.0
    - 4.542619556254522
  n_i: 2
  out_neigh: !!set
    1: null
    2: null
    4: null
    5: null
    7: null
  p_i: 2
  x_0: [0, -1]
  x_H: [0.5, 0.25]

agent9:
  idx: 9
  in_neigh: !!set
    4: null
    5: null
    6: null
  matA:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matA_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matB:
  - - 0.5
    - 0.0
  - - 0.0
    - 0.5
  matB_inter:
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  - - - 0.1
      - 0.0
    - - 0.0
      - 0.1
  matCost:
  - - 6.6835342484811155
    - 0.0
  - - 0.0
    - 6.6835342484811155
  n_i: 2
  out_neigh: !!set
    1: null
    3: null
    5: null
  p_i: 2
  x_0: [-0.5, 1]
  x_H: [-0.25, -0.5]
